n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
n3 = int(input('Digite o terceiro número: '))
maior = max(n1, n2, n3)
menor = min(n1, n2, n3)
print('MAIOR NÚMERO: {}'.format(maior))
print('MENOR NÚMERO: {}'.format(menor))