#FATIAMENTO
#ANÁLISE (LEN): COMPRIMENTO
#(COUNT): CONTAR. EX: frase.count(o): quantas vezes existe a letra 'o'.
#frase.count('o',0,13): contagem da letra 'o', com o fatiamento: conta a letra o, a partir do índice 0 até o índice 12.
#(FIND): ENCONTRAR
#(IN): EXISTE OU NÃO
#TRANSFORMAÇÃO
#(REPLACE): TROCAR
#EX: frase.replace('Python', 'Android'): SUBSTITUI O PYTHON POR ANDROID.
#(UPPER): PRA CIMA | FICA EM MAIÚSCULAS
#(LOWER): FICA EM MINÚSCULAS
#(CAPITALIZE): COLOCA OS CARACTERES PARA MINÚSCILOS E A PRIMEIRA LETRA COLOCA EM MAIÚSCULA.
#(TITLE): QUANTAS PALAVRAS TEM A STRING
#(STRIP): REMOVE TODOS OS ESPAÇOS INÚTEIS, NO INÍCIO E NO FINAL DA STRING.
#(RSTRIP): REMOVE OS ÚLTIMOS ESPAÇOS
#(LSTRIP): REMOVE OS ESPAÇOS DA ESQUERDA (PRIMEIROS)
#DIVISÃO
#(SPLIT): RETIRA OS ESPAÇOS E REFAZ OS ÍNDICE| LITAS DA LISTA
#JUNÇÃO
#(JOIN): JUNTAR